### ISSUE TITLE
Sign Convention of Moment 

### ISSUE THREAD

**Issue by AlexGriffiths526** [ccaprani/pycba#48]
Firstly, I really like this package so thanks for sharing.

I have noticed that when you extract the maximum bending moment using:

beam_results.vRes[1].M.max() 

It returns the maximum sagging moment as a positive value. However, the plot of BM shows sagging to be a negative side. 

This is only a very minor issue but did catch me out.

**Comment by ccaprani** [comment]
Thanks for the nice comments @AlexGriffiths526 . It's a good point.

On this line https://github.com/ccaprani/pycba/blob/4296e7265c8f2ae5d92c387c6eb0d17354e33714/src/pycba/analysis.py#L354, the sign of the bending moment is flipped so that (positive) sagging moments are drawn on the tension face of the beam according to convention. But it does mean that sagging moments appear on the y-axis labels as negative and hogging as positive, which is counter to the convention.

I think the solution is just to use `ax.invert_yaxis()` which will plot downwards positive for the BMD. I'll implement shortly.

Thanks!

**Comment by ccaprani** [comment]
Works well - thanks!

![image](https://github.com/ccaprani/pycba/assets/31228546/83447e8a-6b79-4ae2-a296-fcf673a1cbf4)
